export const MOVEMENT_LOADING = 'MOVEMENT_LOADING';
export const CREATE_MOVEMENT_SUCCESS = 'CREATE_MOVEMENT_SUCCESS';
export const CREATE_MOVEMENT_FAIL = 'CREATE_MOVEMENT_FAIL';
export const RESET = 'RESET';

