export const RATES_LOADING = 'RATES_LOADING';
export const GET_BTC_PRICE_SUCCESS = 'GET_BTC_PRICE_SUCCESS';
export const GET_BTC_PRICE_FAIL = 'GET_BTC_PRICE_FAIL';
export const GET_USD_PRICE_SUCCESS = 'GET_USD_PRICE_SUCCESS';
export const GET_USD_PRICE_FAIL = 'GET_USD_PRICE_FAIL';
export const GET_FASTER_FEE_SUCCESS = 'GET_FASTER_FEE_SUCCESS';
export const GET_FASTER_FEE_FAIL = 'GET_FASTER_FEE_FAIL';
