export const headerTittleTxt: string = 'Create Your Account';
export const headerDescriptionTxt: string = 'You can be a parent, godparent, grandparent or even a favorite aunt. We’ll add the kids after!';
export const descriptionBottomTxt: string = 'By creating this account, I agree that I am a U.S. resident, 18 years or older with a valid bank account. I agree to Goalsetter’s. ';
export const firstNameTxt: string = 'First Name';
export const lastNameTxt: string = 'Last Name';
export const emailTxt: string = 'Email';
export const passwordTxt: string = 'Password';
export const termsTxt: string = 'Terms of Service';
export const buttonTxt: string = 'CREATE FREE ACCOUNT';
